Tosca-Pacer doesn't support https proxy.
When access CSAR file which is URL and the protocol is https by proxy,
it will be error and the information is below:
toscaparser.common.exception.URLException: Failed to reach server
"https://raw.githubusercontent.com/openstack/tosca- parser/master/toscaparser
/tests/data/custom_types/wordpress.yaml". Reason is: Tunnel
connection failed: 503 Service Unavailable.

The reason of the error is urllib doesn't  support https proxy.

JIRA: PARSER-66

Change-Id: I82ec68d533743527fba613cc362e4241494359d4
Signed-off-by: 10013968 <zhang.jun3g@zte.com.cn>
Signed-off-by: shangxdy <shangxdy@shangxdy.local>